### ISSUE TITLE
Script runs only once if launched from toolbar button

### ISSUE THREAD

**Issue by n-timofeev** [Gubaer/josm-scripting-plugin#107]
JOSM 18822, plugin v0.3.0, OpenJDK 21 + [GraalJS 23.0.0](https://github.com/Gubaer/josm-scripting-plugin-graaljs), Windows 11

```
import josm from 'josm'
josm.alert('ok')
```
If I run this script from console, it works, but if I run it from toolbar button, a window appears
![popup](https://github.com/Gubaer/josm-scripting-plugin/assets/71152094/4d544d84-c457-4acc-9ef1-617b65e719ab) 
and script is executed, but only once. The next time the window appears, but script is not running.

**Comment by DavidPx** [comment]
I can confirm this.  It would also be very nice if the engine dialog would not appear with every toolbar button click!

**Comment by Gubaer** [comment]
Thanks for reporting! I'll have time to look into this in December.

**Comment by Gubaer** [comment]
Today, I've published the release [v0.3.1](https://github.com/Gubaer/josm-scripting-plugin/releases/tag/v0.3.1).

Unfortunately, I had to remove support for toolbar icons, which launch a custom script. However, if you click on an entry for a most recently run script in the *Scripting* menu, you no longer have to select a scripting engine. The menu entry remembers the scripting engine chosen for the first invocation.

I plan to implement a custom **toggle dialog** for a list of personal and custom scripts. It will be available in JOSM's right-hand sidebar. I plan to include it in the next release, around March 2024.

**Comment by Filip10** [comment]
@Gubaer I think, that this change has also disabled keyboard shortcuts for scripts saved on toolbar. Am I right?

**Comment by Gubaer** [comment]
> @Gubaer I think, that this change has also disabled keyboard shortcuts for scripts saved on toolbar. Am I right?

Yes, unfortunately, the JOSM and plugin code bases diverged too much. I had to remove a clumsy piece of code from the plugin.

I still plan to provide an alternative. However, currently, I'm behind the announced schedule.
