### ISSUE TITLE
Python plugin support is disabled

### ISSUE THREAD

**Issue by pyrog** [Gubaer/josm-scripting-plugin#27]
Hi,

On Mac OS X Yosemite, the following message is displayed in the _Jython engine_ tab of the _Preference_ pane : 

> **Python plugin support is disabled**
> The scripting plugin can load and run plugins written in **Python**. In order to use this feature the Jython interpreter has to be on the class path when you start JOSM. Currently, it isn't and Python plugin support is therefore disabled.

I tried : 
- severals version of Jython
- copy the Jython.jar in different directory
- changing environnement variable in editing /etc/bashrc or /etc/profile…
- changing VM parameters -Djava.class.path=/Users/xx/jython2.5.3/jython.jar
  ![java vm en](https://cloud.githubusercontent.com/assets/2158081/4880568/305b9620-633d-11e4-8874-a3e57d192e37.png)
- Adding a property in the JNLP file

``` xml
    <resources>
        …
        <property name="java.class.path" value="/Users/xx/jython2.5.3/jython.jar"/>
    </resources>
```

But nothing worked.
This message is displayed in the Java console : 

> WARNING: Missing plugin main version in plugin jython

Any ideas ?

Thanks,

Yves
- Identification: JOSM/1.5 (7643 fr) Mac OS X 10.10
- Java version: 1.7.0_71, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM

**Comment by ViolaineCartONG** [comment]
Hello, I am coming back to this quite a while later... I tried your suggestions but this does not work to me (though I managed to launch JOSM with the -jar command and download the jython.jar file). Talking with @don-vip about that, issue might come from the fact that 'main' class has been removed in JOSM... Does that sound possible? Sorry I am not a developper so Imight be not super accurate here... Hope you can help..

**Comment by Gubaer** [comment]
In my environment (Ubuntu 18.04, JOSM latest (14252), Java 10.0.2 or 1.8.0_191). I can still use this command to launch JOSM. My command looks as follows
```
josm -classpath "./josm-latest.jar:./jython.jar" \
    -Djosm.home=$JOSM_HOME  \
     org.openstreetmap.josm.gui.MainApplication
```
This means
*  `josm-latest.jar` and `jython.jar` are in the current directory
* I have an environment variable `JOSM_HOME`  (full path of JOSMs home directory) 

If you download Jython in the JOSM preferences dialog, the jar is saved in `$JOSM_HOME/plugins/scripting/jython-standalone-2.7.0.jar`. 

In this case, you should start JOSM with the following command:
```
josm -classpath "./josm-latest.jar:./$JOSM_HOME/plugins/scripting/jython-standalone-2.7.0.jar" \
    -Djosm.home=$JOSM_HOME  \
     org.openstreetmap.josm.gui.MainApplication
```

Hope this helps!

**Comment by ViolaineCartONG** [comment]
hi @Gubaer , thanks for your reply. 

Still when I use josm instead of java as you mentionned here, I get an "invalid option" error
JOSM : option invalide -- c (i have tried with -classpath --classpath -cp --cp : always the same)

And when I use java i get this : 
Error : impossible to find main class : org.openstreetmap.josm.gui.MainApplication

I entered my full path to avoid having to define a environment variable (for testing), and withdrew the -Djosm.home as I use the default folders...

If you can help, this would be very much appreciated...

**Comment by don-vip** [comment]
@ViolaineCartONG on Windows the Java classspath separator is a semicolon (`;`)

**Comment by ViolaineCartONG** [comment]
thks @don-vip but I am on linux too... my config : linux mint 18.3 kde (ubuntu 16.04), josm 14289, java 1.8.0_181 if this helps...
