### ISSUE TITLE
#11203 - Problem with Jython script

### ISSUE THREAD

**Issue by don-vip** [Gubaer/josm-scripting-plugin#28]
Hi,
Someone complains about a problem with a Jython script:
https://josm.openstreetmap.de/ticket/11203

Cheers,
Vincent

**Comment by Gubaer** [comment]
Tracking this in the [JOSM track ticket](https://josm.openstreetmap.de/ticket/11203).

**Comment by Gubaer** [comment]
I'm wondering why `com.google.common.collect.MapMaker` is beeing loaded. It is neither part of `josm.jar`nor of `jython-2.5.3.jar`, as far as I can tell.
How does you local environment look like? OS? Jython version? What are you trying to do?

**Comment by marcobra** [comment]
Please close i installed the jython installer from here http://www.jython.org/downloads.html not from plugin itself add the path into settings and all works good...
