### ISSUE TITLE
 merge  roads using scripting plugin. 

### ISSUE THREAD

**Issue by Rub21** [Gubaer/josm-scripting-plugin#31]
@Gubaer  :
This is nice tool :+1: 
I have a question, is there a way to merge two roads by id in JavaScript? ,  Might be as a next function, I 

```
var command = require("josm/command");
var way3 = command.merge(way1.id,wa2.id);

```

Thanks.

**Comment by alex85k** [comment]
It depends on what do you mean by 'merge roads'. Glueing them together like C josm command?

**Comment by Rub21** [comment]
@alex85k : I mean  `combine two ways`  the command  exist in JOSM , but I don't know how can I use it from scripting 
![screenshot from 2015-10-21 15 32 06](https://cloud.githubusercontent.com/assets/1152236/10649341/1dcbef3c-7809-11e5-9c97-403ceca825d3.png)

**Comment by Gubaer** [comment]
Created a new release 30720. You can update the plugin from the JOSM preferences dialog, provided you are working with JOSM latest (>= 8906).

In the scripting console you can then use the following snipped which has the same effect as invoking _Combine Way_  from the JOSM menu:
```javascript
var cmd = require("josm/command");
cmd.combineSelectedWays();
```

There is an alternative API which combines a collection of ways in the active layeer and which you you can use as follows:

```javascript
var cmd = require("josm/command");
var layers = require("josm/layer");
var ds = layers.activeLayer.data; 
var ways  = [ds.way(1), ds.way(2), ds.way(3)];
 
// pass in an array of ways...
cmd.combineWays(ways);
// ... or the individual ways ...
cmd.combineWays(ds.way(1), ds.way(2), ds.way(3));
// ... or any combination thereof. 
```
