### ISSUE TITLE
provide script examples 

### ISSUE THREAD

**Issue by Gubaer** [Gubaer/josm-scripting-plugin#33]
Hi Gubaer, could you please help with some script examples for your plugin Scripting, which edit something in geometry or adding something, on Python or Java Script? I managed to launch scripts HelloWorld.js, WaysPropertiesOfARoute.jy, RWN2Garmin.py and AddHouseNumbers.groovy, but it does not help to understand how to edit/add geometry. I made/modify some scripts for CommandLine plugin from Hind, like advanced orthogonalization, adding ellipse and grid. I think it is worth to port some scripts from CommandLine to your Scripting to have better chances for them to work in future JOSM, but to do so I need some examples how to use data model in your plugin. OverQuantum (talk) 11:30, 13 February 2016 (UTC)

submitted on Gubaers [OSM Wiki Page](http://wiki.openstreetmap.org/wiki/User_talk:Gubaer)

**Comment by Gubaer** [comment]
Are you aware of this help page for [manipulating data using the JS API](http://gubaer.github.io/josm-scripting-plugin/doc/manipulating-data.html)?

**Comment by OverQuantum** [comment]
Well, I read it, but it does not help much - there is no complete example of something useful, like adding circle to current layer or collapsing selected object to 1 node.

**Comment by Gubaer** [comment]
I see.  I'll see what I can do. What do you mean with "adding circle to current layer"? Do you want to add a bunch of nodes to the the current layer, such that they form a circle with a given radius?

**Comment by OverQuantum** [comment]
> What do you mean with "adding circle to current layer"? Do you want to add a bunch of nodes to the the current layer, such that they form a circle with a given radius?

Yes, but with a way also.

**Comment by Gubaer** [comment]
Did you already try to implement something like this, using  [this docu](http://gubaer.github.io/josm-scripting-plugin/doc/manipulating-data.html)? If yes, please post here what you tried and where  you have a specific problem. Or send me a pointer to your code on Github. 
If you didn't try yet, why not? What's missing?

**Comment by OverQuantum** [comment]
1) Following code produces error message "Failed to execute a script. Error message:TypeError: Cannot call property withPosition in object [JavaPackage org.openstreetmap.josm.builder.NodeBuilder]. It is not a function, it is "object". (inlineScript#7) At:line 7, column 0"

```
var josm = org.openstreetmap.josm;
var builder= josm.builder;
var nb = builder.NodeBuilder;
var layer = josm.layers.activeLayer;
var ds = layer.data;
var n1;
n1 = nb.withPosition(1,1).create();
```
2) Following code produces error "Script execution has failed. org.mozilla.javascript.JavaScriptException: Error: Module "josm/util" not found. (inlineScript#1)" in JOSM console

```
var util = require("josm/util");
util.println("Hello world!");
```

**Comment by Gubaer** [comment]
ad 2) Works in my JOSM installation, though. I have JOSM 9572 and Scripting 30722. What versions are you  working with?

**Comment by OverQuantum** [comment]
JOSM 9329 (current josm-tested.jar), Scripting 30722
Java Version 1.7.0_67
Both scripts launched using Scripting Console and Rhino Engine.

**Comment by Gubaer** [comment]
What OS? Linux or Windows?

**Comment by OverQuantum** [comment]
WinXP SP3, 32 bit

**Comment by Gubaer** [comment]
Uhh, this is quite old. Unfortunately, I can neither test nor reproduce on this platform.

BTW: you may consider to migrate to another OS, [WinXP isn't supported anymore by Microsoft](https://www.microsoft.com/windows/en-us/xp/default.aspx)

**Comment by Dylansc22** [comment]
Hi Gubaer, thank you for everything you've put together with this documentation, but I too am finding large gaps in understanding how to connect the documentation to concrete use cases. 

Specifically I am trying to use the JOSM Scripting plugin to programmatically Split Ways IDs through my small (smaller than a city) .osm .pbf file via the Rhino Javascript command.

```
function current_layer() {
    var layers = require("josm/layers");
    return layers.activeLayer;
}

//Define the function
function SplitWaysAndAssignNewIDs(){
   

    var util = require("josm/util");
    var command = require("josm/command");
    var console = require("josm/scriptingconsole");
    var split = org.openstreetmap.josm.actions.SplitWayActions;    

    var layer = current_layer();
    if (layer == null) return;
    var dataset = layer.data;

//Select my Node of Interest which is a member of a Given Way
var sampleNodeInWay= dataset.query("id:175494043");

//Run the Split command - This code is wrong, and I don't know how to fix it!
//I'm sorry but I cannot understand the documentation about declaring java classes in javascript
split.runOn(sampleNodeInWay); 

var newWays = dataset.query("type:way")

//Assign a New OSM ID to each half of the Way I just split
for (j = 0; j < newWays .length; j++) {
    // newWays [j].setOsmId(999000000+j,1); 
 }

}

//Run the function
SplitWaysAndAssignNewIDs();
```

Don't worry I am not uploading this weird modified dataset to OSM. This is just for a personal offline project. @Gubaer could you please provide some feedback on my code? is there something simple I'm missing in using the SplitWayAction Class? How can I fix the `split.runOn(sampleNodeInWay); ` line of code?

Thank you kindly for your time, and thank you in advance for your reply! Best wishes. 
- Dylan

**Comment by Gubaer** [comment]
I applied two fixes (FIX A and FIX B) to the script you provided. They result in a script which uses JOSMs `SplitWayAction::runOn()` method on a dataset and not on an individual way.

You will probably have to tinker around with the script and try to apply it to the specific dataset you want to manipulate.

```javascript
function current_layer() {
    var layers = require("josm/layers");
    return layers.activeLayer;
}

//Define the function
function SplitWaysAndAssignNewIDs(){
   

    var util = require("josm/util");
    var command = require("josm/command");
    var console = require("josm/scriptingconsole");
    var split = org.openstreetmap.josm.actions.SplitWayAction;    

    var layer = current_layer();
    if (layer == null) return;
    var dataset = layer.data;

   //Select my Node of Interest which is a member of a Given Way
   var sampleNodeInWay= dataset.query("id:38589360");

   // FIX A: Select the way in the dataase 
   dataset.selection.add(sampleNodeInWay);

   // FIX B: the SplitWayAction command operates on a dataset with selected ways, not on the
   // individual way
   split.runOn(dataset); 

   var waySplitInHalf = dataset.query("type:way")

   //Assign a New OSM ID to each half of the Way I just split
   for (j = 0; j < waySplitInHalf.length; j++) {
       // waySplitInHalf[j].setOsmId(999000000+j,1); 
   }
}

//Run the function
SplitWaysAndAssignNewIDs();
```
