### ISSUE TITLE
No way to add features to an existing layer?

### ISSUE THREAD

**Issue by bdiscoe** [Gubaer/josm-scripting-plugin#34]
The documentation for "Manipulating data" shows how to create nodes, ways, etc.
However, the features are not much use, because they are not actually added to any layer.
The documentation for WayBuilder says it is possible to pass a dataset to a constructor.
But, there is no description or example of how this constructor is meant to be called.

I tried:
1. var wbuilder = require("josm/builder").WayBuilder(dataset);
2. var wbuilder = require("josm/builder").new WayBuilder(dataset);
3. var wbuilder = require("josm/builder").WayBuilder;
  var wbuilder2 = wbuilder.WayBuilder(dataset);
4. var wbuilder = require("josm/builder").WayBuilder;
  var wbuilder2 = wbuilder.new WayBuilder(dataset);
5. var wbuilder = require("josm/builder");
  var wbuilder2 = new WayBuilder(dataset);

None of these work; they return null or give an error.

It would be very, very useful to have an example which actually creates some feature and adds it to the current layer, if such a thing is possible?

**Comment by Gubaer** [comment]
Please paste the following fragment in the scripting console and run it. This should work. Unfortunately, there is a bug in the documentation for [WayBuilder](http://gubaer.github.io/josm-scripting-plugin/apidoc/classes/WayBuilder.html). I'll fix this shortly. Until then I leave this issue open.

```javascript
// import WayBuilder 
var WayBuilder = require("josm/builder").WayBuilder;
// import scripting console 
var console = require("josm/scriptingconsole");
// create an alias for the fully qulalified java name of DataSet
var DataSet = org.openstreetmap.josm.data.osm.DataSet;

// create the new dataset 
var ds = new DataSet();
// creae the way builder whichs inserts ways to the datayset 
var wbuilder = new WayBuilder(ds);
// create a new way 
var way = wbuilder.create();


// output the id if the new way
console.println("new way: " + way.id);
// output the number  ways in the dataset 
console.println("number of ways in dataset: " + ds.ways.size());

```

**Comment by Gubaer** [comment]
Please check out the improved documentation for [WayBuilder](http://gubaer.github.io/josm-scripting-plugin/apidoc/classes/WayBuilder.html). It now includes sample code to create a `WayBuilder` with an underlying dataset.
