### ISSUE TITLE
dataset.selection seems to not work

### ISSUE THREAD

**Issue by bdiscoe** [Gubaer/josm-scripting-plugin#35]
I tried this:

var layers = require("josm/layers");
var layer = layers.activeLayer;
var dataset = layer.data;
var sel = dataset.selection;
sel.clearAll();

that had no effect at all.

I also tried selecting a way, using a known existing id:

var way1 = dataset.way(4219524321);
sel.set(way1);

This resulted in: Error message:ReferenceError: "HashSet" is not defined.(jar:file:/.....js/josm/mixin/DataSetMixin.js#349) At: link 349, column 0

**Comment by Gubaer** [comment]
Fixed in 82d6bb0adf5ee7433f43fd6458c9e1600264c20c and in b5786fd2f662fa16303130a0e810d7f317b25c0e on feature branch.

Will soon (in the next couple of days) merge to master and release an updated version of the scripting plugin.

**Comment by Gubaer** [comment]
Published a new version of the plugin which should include a fix for this issue. Please update the plugin in JOSM.
