### ISSUE TITLE
PyException with qat-script keepright mode

### ISSUE THREAD

**Issue by don-vip** [Gubaer/josm-scripting-plugin#36]
We have received a bugreport: https://josm.openstreetmap.de/ticket/13351

Is this a Python/Jython integration problem with the plugin?

**Comment by Gubaer** [comment]
The [Wikipage](https://josm.openstreetmap.de/ticket/13351) says: "The script works only with Java version 7". I guess I doesn't work anymore with the latest scripting plugin build. It is compiled for Java 8.

Created another [issue for qat_script](https://github.com/simone-f/qat_script/issues/9).

**Comment by Gubaer** [comment]
Old issue with no progess. Tagging as stale and closing.
