### ISSUE TITLE
DataSetMixin.save() misses closing </osm> tag

### ISSUE THREAD

**Issue by Fonant** [Gubaer/josm-scripting-plugin#37]
The DataSetMixin save() method works fine apart from it is missing the </osm> tag at the end of the file.

Perhaps there's a OsmWriter.footer() method call missing?

**Comment by Gubaer** [comment]
Thanks for reporting! I'll have a look but it will take some time because I'm travelling until end of september.

**Comment by Gubaer** [comment]
Published a new release of the plugin compatible with JOSM tested (10966) and newer. Please upgrade the scripting plugin in the JOSM preferences dialog.
