### ISSUE TITLE
Update Groovy Release

### ISSUE THREAD

**Issue by drkludge** [Gubaer/josm-scripting-plugin#38]
Please update `resources/script-engine-jars.properties`  to https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.4.7/groovy-all-2.4.7.jar from the current 2.2.2 release.  I have been using this release for some time now with no issues.

**Comment by Gubaer** [comment]
thanks, @drkludge, I've published a new plugin release which includes the download URL for groovy 2.4.7
