### ISSUE TITLE
No output logs?

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#45]
While browsing the quite well explained documentation (thanks!), I stumbled upon an issue: I fail to output anything from the console:

```js
var out = java.lang.System.out;
out.println("Hey?");

//or 
var util = require("josm/util");
util.println("Hello??");
```

![capture d ecran de 2017-06-07 11-39-52](https://user-images.githubusercontent.com/1451988/26872311-5939c94e-4b76-11e7-83e0-beb3c0df50c8.png)

Where should these logs be display?

Using JOSM 12324 / scripting 30765.

**Comment by bagage** [comment]
EDIT: ok they appear at the same location of JOSM ones. But what is the bottom part of the scripting console for then?

**Comment by Gubaer** [comment]
There is dedicated JavaScript module [scriptingconsole](http://gubaer.github.io/josm-scripting-plugin/apidoc/modules/josm_scriptingconsole.html) which provides an API to write to the bottom part of the scripting console. It also provides an API to clear, show, hide, toggle the console.

**Comment by SwiftFast** [comment]
In Linux, the print commands output to stdout and not to the console. (when not using the module)

**Comment by Gubaer** [comment]
Yes, you're right. That's why there's is the dedicated JavaScript module [scriptingconsole](http://gubaer.github.io/josm-scripting-plugin/apidoc/modules/josm_scriptingconsole.html) .

Instead of 
```javascript
print("Hello World!");
```
use 
```javascript
var console = require("josm/scriptingconsole");
console.print("Hello world!");
```

**Comment by bagage** [comment]
OK, thanks! Might be a worth adding it the documentation maybe because I couln't find it while browsing other.
Anyway thanks all!
