### ISSUE TITLE
Can we trigger a script from outside of JOSM?

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#47]
It is possible to invoke a script from outside of JOSM, for instance via Remote Control?
It may be risky but maybe there's a (secure) way of triggering some script?

**Comment by Gubaer** [comment]
So far I didn't add such a feature. It could be done, though. The scripting plugin could for instance listen on a local port for commands, similar to the Remote Control feature in JOSM.

**Comment by drkludge** [comment]
There is a plugin called [ExtTools](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/ExtTools).  There's not much information.  You are supposed to generate a JOSM formatted .osm file.  That may not be helpful if you are trying to accomplish something on the data that is already loaded.  It is still worth a look.

**Comment by SwiftFast** [comment]
JOSM can already run a script on startup. You can write a startup script and then call JOSM from the command line, it will execute the script. Commandline scripts can be invoked in countless ways, including TCP, etc.

If you want to also *select* which script to run, here is a hack to do this: JOSM can open a file via command line parameters: `josm --download=<filename>`.

So, the procedure is as follows: If you want to run script1, you call `josm --download=<path>/dummy1`. Similarly, to run script2, you call `josm --download=<path>/dummy2`. Where dummy1 and dummy2 are just blank or minimal files, e.g. gpx files.

 Now, when your startup script runs, it scans the JOSM layer and figures out which file was open, and based on that, it decides which script to run.
