### ISSUE TITLE
action.addToToolbar({at: "end"});

### ISSUE THREAD

**Issue by bjohas** [Gubaer/josm-scripting-plugin#52]
Using action.addToToolbar({at: "end"}); gives the error 

Wrapped java.lang.IllegalArgumentException: Error: Null as list element in preference setting.
jar...scripting.jar!/js/josm/mixin/JSActionMixin.js#356

and the menu bar item is not added.

**Comment by Gubaer** [comment]
The patch fixes the IllegalArgumentException. Unfortunately, adding a JSAction is still broken, though. Whatever my intention was at the time when I implemented JSAction and JSActionMixin: the code looks pretty messy ;-(

**Comment by bjohas** [comment]
Many thanks - so there isn't a way of adding anything to the toolbar at the moment? Do you have a suggestion for how one might construct a simple UI, other than via the main menu?

**Comment by RubenGeo** [comment]
@ bjohas

I was trying to use your partial solution. I was, however, only able to add the original menu items to the toolbar (such as file >  open and file > save) and not the menu items created using JSAction. Could you explain how you did this?

**Comment by bjohas** [comment]
Hi @RubenGeo ,

thanks for giving this a go! Can you have a look through the instructions at http://bjohas.de/go/mmjosm (somewhat towards the end of the google doc)? I've set the document so that anybody can comment, so if there's anything unclear (in the scripting section), just add a comment, and we can clarify so that others can benefit.

**Comment by RubenGeo** [comment]
@bjohas 

Great very clear instructions! Thanks for the help!

**Comment by bjohas** [comment]
You're welcome - glad it was useful!
