### ISSUE TITLE
Compatibility issue with latest JOSM

### ISSUE THREAD

**Issue by don-vip** [Gubaer/josm-scripting-plugin#55]
Hello,
I did a lot of internal refactoring in JOSM core recently, see https://josm.openstreetmap.de/ticket/15182
It seems at least https://josm.openstreetmap.de/changeset/12687/josm/ is a breaking change for your plugin, sorry I didn't notice it earlier, see https://josm.openstreetmap.de/ticket/15206

**Comment by Gubaer** [comment]
Thanks for reporting!  I'll take care of it next week, currently on vacations.

**Comment by Gubaer** [comment]
Fixed in 1a2a02d102555, published new plugin version in c223beb7a3113d687ac5015d7aa5f3266423d330
