### ISSUE TITLE
How to launch tests?

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#56]
I tried to run `./gradlew test` but nothing seems to be run -- what's the proper approach to launch all tests that are present for the plugin?

**Comment by Gubaer** [comment]
Running tests is not sufficiently documented :-(.  `gradlew test` doesn't work at the moment. 
I'll take care about it next week, currently I'm on vactions. Will keep you posted.

**Comment by Gubaer** [comment]
`gradlew test` now executes the unit tests for the plugin implemented in java and groovy. The [README](https://github.com/Gubaer/josm-scripting-plugin/blob/master/README.md) now includes a howto for executing unit tests.
