### ISSUE TITLE
Possible bug when updating coordinates of elements

### ISSUE THREAD

**Issue by SafwatHalaby** [Gubaer/josm-scripting-plugin#59]
I'm iterating a collection of elements that were downloaded from the OSM server.

```
///etc...foreach element
{
 element.lat = 34;
 element.lon = 35;
}
```

For some reason, the above code will correctly set lon to 35, but lat will be set to the element's previous longitude. It's as if this is being executed:

```
element.lat = element.lon;
element.lon = 35;
```

The following variation seems to work fine:

```
///etc...foreach element
{
 element.pos = {lat: 34, lon: 35}
}
```

**Comment by Gubaer** [comment]
Fixed in ff38789. Deployed a new release. Please update from JOSM preferences dialog. Requires JOSM >= 13007.

**Comment by SafwatHalaby** [comment]
You're doing an amazing job maintaining this plugin. Thank you.

**Comment by SafwatHalaby** [comment]
Slightly offtopic. These are bot scripts based on this plugin: https://github.com/SafwatHalaby/osm-bot. You may want to check them out.

**Comment by Gubaer** [comment]
Interesting! One of my customers, a local public transport provider, might be interested in your GTFS bot!

**Comment by SafwatHalaby** [comment]
For more info about the gtfs script, see [this forum post](https://forum.openstreetmap.org/viewtopic.php?pid=665110#p665110) and [this one](https://forum.openstreetmap.org/viewtopic.php?pid=665592#p665592).  Conflicts are resolved with a nice trick. A dedicated Wiki page with good documentation will be set-up soon, once I finish testing / changing things.

Also, I may eventually make the script emit mappers vs gtfs conflict logs that could be given back to the provider for feedback.

**Comment by SafwatHalaby** [comment]
Wiki page: https://wiki.openstreetmap.org/wiki/User:SafwatHalaby#SafwatHalaby_bot (work in progress)
