### ISSUE TITLE
Escaping issue when printing "{"

### ISSUE THREAD

**Issue by SafwatHalaby** [Gubaer/josm-scripting-plugin#60]
Plugin:

```
var util = require("josm/util");
util.println("{");
```

JOSM pops up this error:

```
Failed to execute the script file 'printBug.js'.

Error message:Wrapped java.lang.IllegalArgumentException: Unmatched braces in the pattern. 
(jar:file:/home/osm/.josm/plugins/scripting.jar!/js/josm/util.js#379)
At: line 379, column 0
```

**Comment by Gubaer** [comment]
`util.println()` and `util.print()` rely on the Java class `java.text.MessageFormat`.

You have to escape meta-characters like `}`, `{` or `'` with a leading `'`.

I added this info to the API documentation, see 4f7f5898bc92a5430d471404b75cdc4fb3809645
