### ISSUE TITLE
Error with module josm/layers in JOSM version 13265

### ISSUE THREAD

**Issue by RubenGeo** [Gubaer/josm-scripting-plugin#63]
The property active layer (http://gubaer.github.io/josm-scripting-plugin/apidoc/modules/josm_layers.html#activeLayer) is not working anymore since I updated JOSM from version  13170 to 13265.

`var layers = require("josm/layers");
layer =  layers.activeLayer;`

It now returns the following error: 

> Error message:Java class "org.openstreetmap.josm.Main" has not public instance field or method named "getLayerManager".

**Comment by Gubaer** [comment]
thanks, I'll have a look! By the end of the week I'll publish a new release!

**Comment by bdiscoe** [comment]
I'm having the same issue, I depend heavily on the scripting plugin so really looking forward to the fix, thanks!

**Comment by Gubaer** [comment]
I've published a new release. It includes two patches provided by @floscher. They fix a lot of calls to now removed JOSM APIs. 

Please update the scripting plugin from the JOSM preferences dialog.

**Comment by RubenGeo** [comment]
@Gubaer Awesome!! Thank you!
