### ISSUE TITLE
Cannot find method HelpAwareOptionPane::showOptionDialog with latest JOSM

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#74]
It works with 14178, but it fails with latest JOSM version 14382:

![image](https://user-images.githubusercontent.com/1451988/47679334-57eca680-dbc4-11e8-998a-3d0785e58179.png)

I do not see any changes in HelpAwareOptionPane.java file since May, though.

**Comment by bagage** [comment]
Can be reproduce with a simple `josm.alert('test')`

**Comment by bagage** [comment]
Up to JOSM 14249, scripting 30787 works OK. But starting with JOSM 14256, both scriptingplugin versions 30787 and 30791 are broken.

**Comment by Gubaer** [comment]
Thanks for reporting! Should be fixed in plugin release 30792 (JOSM >= 14256 required). Please update the plugin in JOSMs preferences dialog.

**Comment by bagage** [comment]
Confirming it just reworks. Thanks a lot @Gubaer!!
