### ISSUE TITLE
javax.swing.JOptionPane.showInputDialog method not found

### ISSUE THREAD

**Issue by kurly1** [Gubaer/josm-scripting-plugin#75]
I created a script which I was runing with JOSM 13710 and scripting plugin 30785 and older versions.
Today I updated to JOSM 14382 and the scripting plugin was updated to 30792 and my script trows an error with this versions.

var JOptionPane = javax.swing.JOptionPane; 
var layers = require("josm/layers");
var layer = layers.activeLayer;

function selectLayers() {
  // read all layers in a array
  var numlayers = layers.length;
  var arrLayers = []
  var j = 0;

  for (i = 0; i < numlayers; i++) {
    if ( layers.get(i).name !== layer.name ) {
      arrLayers[j] = layers.get(i).name;
      j++;
    }
  }

  // select the layer wiht the elevation data
  selection = JOptionPane.showInputDialog(Main.parent, "Select layer wiht elevation data", "Input", JOptionPane.INFORMATION_MESSAGE, null, arrLayers, null);

  return selection;
}

This trows the following error:

Can't find method javax.swing.JOptionPane.showInputDialog(object, string, string, number, null, object, null).

Is this a bug or is this java class no longer supported?

Is there an other way to create a windows with a drop down selection box?

**Comment by Gubaer** [comment]
Please try the following snippet. This works for me in JOSM 14418.

```javascript
var JOptionPane = javax.swing.JOptionPane;
var MainApplication = org.openstreetmap.josm.gui.MainApplication;
var selection = JOptionPane.showInputDialog(
        // use this a parent component! Main.parent has recently been removed 
        // from the JOSM code base recently
        MainApplication.getMainFrame(),       // the parent component
        "Select layer wiht elevation data",   // message
        "Input",                              // dialog title
        JOptionPane.INFORMATION_MESSAGE,      // kind of dialog
        null,                                 // no icon
        ["A", "B", "C"],                      // selection options
        "B");                                 // initial selection
```
