### ISSUE TITLE
Accentued characters not supported when invoked from script file (éèàê)

### ISSUE THREAD

**Issue by bagage** [Gubaer/josm-scripting-plugin#76]
It seems that the plugin does not handle utf-8 strings properly? When you use `josm.alert("é");` in the scripting console, it displays properly `é` on the screen, however if you save it in a file `test.js` and launch it via `Scripting -> Run`, you end up with:

![image](https://user-images.githubusercontent.com/1451988/48573814-bed0c600-e90d-11e8-8fed-e0e2919625ef.png)

**Comment by Gubaer** [comment]
Published plugin release 30793. Please update the plugin in JOSMs preferences dialog.

Thanks, @floscher, for the patch!

**Comment by bagage** [comment]
Thanks @floscher and @Gubaer for the super fast fix and release!
