### ISSUE TITLE
wrapped java.lang.nullpointerexception for JSaction

### ISSUE THREAD

**Issue by RubenGeo** [Gubaer/josm-scripting-plugin#78]
Using the sample found on http://gubaer.github.io/josm-scripting-plugin/apidoc/mixins/JSActionMixin.html

```
var JSAction = require("josm/ui/menu").JSAction;

// adds a new action to the JOSM edit menu
new JSAction({name: "My Action"})
   .addTo(josm.menu.get("edit"));
```
I am getting the following error:
`wrapped java.lang.nullpointerexception`

Do you know what might have caused this?

Thank you for your answer!

**Comment by Gubaer** [comment]
Fixed in plugin release 30794, please update the plugin from JOSMs preference dialog.

Note that the code snipped above should be:
```javascript
var JSAction = require("josm/ui/menu").JSAction;

// adds a new action to the JOSM edit menu
new JSAction({name: "My Action"})
   // .addToMenu(), not addTo()
   .addToMenu(josm.menu.get("edit"));
```
The [API documentation](https://gubaer.github.io/josm-scripting-plugin/apidoc/mixins/JSActionMixin.html) is fixed too.

**Comment by RubenGeo** [comment]
Thanks for the fix!
