### ISSUE TITLE
Example scripts are unaccessible

### ISSUE THREAD

**Issue by KorneySan** [Gubaer/josm-scripting-plugin#83]
Link to [https://github.com/Gubaer/josm-scripting-plugin/tree/master/scripts example scripts] is broken (result is 404).

**Comment by Gubaer** [comment]
Fixed the link in the [doc page](https://gubaer.github.io/josm-scripting-plugin/doc/documentation.html).

Thanks for reporting!

**Comment by Gubaer** [comment]
Fixed in the [README](https://github.com/Gubaer/josm-scripting-plugin), too.
