### ISSUE TITLE
Cannot load JOSM's Main Class

### ISSUE THREAD

**Issue by MikeTho16** [Gubaer/josm-scripting-plugin#87]
I seem to be unable to load or access JOSM's "Main" class.  However, I am able to load other JOSM classes. The code below illustrates the issue:

```
  var console = require("josm/scriptingconsole");

  josm.alert(org.openstreetmap.josm.Main);
  // Does not work, response is:
  // [javaPackage org.openstreetmap.josm.Main] 
  // should be "class org.openstreetmap.josm.Main"

  josm.alert(org.openstreetmap.josm.data.osm.AbstractPrimitive);
  // Works, response is:
  // class org.openstreetmap.josm.data.osm.AbstractPrimitive

  var Main = java.lang.Class.forName("org.openstreetmap.josm.Main");
  // Error message:Wrapped java.lang.ClassNotFoundException: org.openstreetmap.josm.Main ...

  var AbstractPrimitive = java.lang.Class.forName("org.openstreetmap.josm.data.osm.AbstractPrimitive");
  // Works (no error message)
```

**Comment by Gubaer** [comment]
`org.openstreetmap.josm.Main` is abstract. Try `org.openstreetmap.josm.gui.MainApplication` instead, this should work.

**Comment by MikeTho16** [comment]
I looked into this further, and it seems that with the current version of JOSM there is no longer an `org.openstreetmap.josm.Main ` class, which is why   
` josm.alert(org.openstreetmap.josm.Main);`   
gave a response of:   
`[javaPackage org.openstreetmap.josm.Main]`
