### ISSUE TITLE
Example: dataset query with options

### ISSUE THREAD

**Issue by pyrog** [Gubaer/josm-scripting-plugin#88]
How to [query](http://gubaer.github.io/josm-scripting-plugin/apidoc/mixins/DataSetMixin.html#query) a dataset in javascript with i.e. `regexSearch` or `caseSensitive`  option ?

```javascript
ds = josm.layers.activeLayer.data;
r = ds.query("operator=orange", caseSensitive=false);
```
Return only `orange`, not `Orange`.

Same result with default value.
```javascript
ds = josm.layers.activeLayer.data;
r = ds.query("operator=orange");
```

**Comment by pyrog** [comment]
JOSM run on macOS 11.2.1 "Big Sur".

options don't work with CTRL+F in JOSM, so it's seem to be an JOSM issue on macOS 😢

**Comment by pyrog** [comment]
Seem that regular expression are working without `regexSearch` option.
```javascript
// Search "ref:FR:Orange"~".*-PT.*"

ds = josm.layers.activeLayer.data;
r = ds.query("\"ref:FR:Orange\"~\".*-PT.*\"");

```

**Comment by Gubaer** [comment]
> How to [query](http://gubaer.github.io/josm-scripting-plugin/apidoc/mixins/DataSetMixin.html#query) a dataset in javascript with i.e. `regexSearch` or `caseSensitive` option ?
> 
> ```js
> ds = josm.layers.activeLayer.data;
> r = ds.query("operator=orange", caseSensitive=false);
> ```

Try the following instead:

```js
var ds = josm.layers.activeLayer.data;
// note:  operator:orange instead of operator=orange
// note: {caseSensitive:false} as an object literal, instead of caseSensitive=true
var r = ds.query("operator:orange", {caseSensitive:false});
```
It works with me (Ubuntu), hope it works on macOS 11.2.1 "Big Sur" too.
