### ISSUE TITLE
Can't install on JOSM 18323

### ISSUE THREAD

**Issue by pl71** [Gubaer/josm-scripting-plugin#92]
I can't install on JOSM 18323;
Class org.openstreetmap.josm.plugins.scripting.ScriptingPlugin not found.

**Comment by Gubaer** [comment]
I can't reproduce this. On my ubuntu box it works with JOSM 18327. Can you be more specific? What's your OS? What are your steps before you see this message?

**Comment by pl71** [comment]
Windows. But now plugin installs normally. JOSM 18360

**Comment by Gubaer** [comment]
Ok, great news! Closing the issue.
