### ISSUE TITLE
Square bracket notation

### ISSUE THREAD

**Issue by pl71** [Gubaer/josm-scripting-plugin#94]
Looks like subject [notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#objects_and_properties) for objects is not available within the JS engine supplied. Could you please confirm?
At the same time I can't use other JS engines.

**Comment by Gubaer** [comment]
The plugin includes the [Rhino](https://mozilla.github.io/rhino/) scripting engine. JavaScript support is therefore somewhat restricted:

* Rhino only supports a subset of modern ECMAScript versions, see its [compatibility table ](https://mozilla.github.io/rhino/compat/engines.html) for ES2015

* The plugin currently doesn't include the most recent version of the Rhino engine. It definitely should prepare a new build with the latest Rhino release.

I plan to replace Rhino with GraalVM in the scripting plugin; see the branch [graalvm](https://github.com/Gubaer/josm-scripting-plugin/tree/graalvm). Unfortunately, I'm somewhat stuck with this work. I hope to publish a new plugin release, which will be migrated to GraalVM and support modern ECMAScript dialects soon.

**Comment by pl71** [comment]
Thank you. Keep this great work. With more samples it could be very useful. Meanwhile, I found some workaround for square bracket notation.

**Comment by Gubaer** [comment]
Version [v0.2.0] can now be used with GraalJS which supports modern ECMAScript versions including square bracket notation. Here's an example:

![image](https://user-images.githubusercontent.com/249051/172008096-7102ce0e-7c24-45fa-98ad-66f0238d9cca.png)


[v0.2.0]:https://github.com/Gubaer/josm-scripting-plugin/releases/tag/v0.2.0
